[package]
name = "pedals"
version = "0.1.0"
authors = ["Peter Stuart <peter@peterstuart.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
cpal = "0.13.3"
ringbuf = "0.2.4"

[lib]
name = "pedals"
path = "src/lib.rs"

[[bin]]
name = "pedals"
path = "src/main.rs"